export const gyms = [
  {
    id: "1",
    name: "Gold's Gym Indiranagar",
    description: "Premium fitness center with world-class equipment and personal training.",
    location: "Indiranagar, Bangalore",
    lat: 12.9719,
    lng: 77.6412,
    rating: "4.8",
    distance: "1.2 km",
    price: "₹299",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=2070&auto=format&fit=crop",
    trending: true,
    tags: ["Free Parking", "Steam Room", "AC"],
    plans: [
      { id: "p1", type: "DAY", price: 299 },
      { id: "p2", type: "WEEK", price: 1499 },
      { id: "p3", type: "MONTH", price: 3999 },
    ],
    amenities: ["AC", "Parking", "Locker", "Shower", "Steam"],
  },
  {
    id: "2",
    name: "Cult Fit HSR Layout",
    description: "Holistic fitness center offering group workouts and yoga.",
    location: "HSR Layout, Bangalore",
    lat: 12.9141,
    lng: 77.6411,
    rating: "4.9",
    distance: "0.8 km",
    price: "₹199",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=2070&auto=format&fit=crop",
    trending: false,
    tags: ["Group Workouts", "Yoga"],
    plans: [
      { id: "p4", type: "DAY", price: 199 },
      { id: "p5", type: "WEEK", price: 999 },
      { id: "p6", type: "MONTH", price: 2499 },
    ],
    amenities: ["AC", "Locker", "Shower"],
  },
  {
    id: "3",
    name: "Power House Gym",
    description: "Hardcore bodybuilding gym for serious enthusiasts.",
    location: "Koramangala, Bangalore",
    lat: 12.9352,
    lng: 77.6245,
    rating: "4.5",
    distance: "2.5 km",
    price: "₹150",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=2070&auto=format&fit=crop",
    trending: true,
    tags: ["Heavy Weights", "Open 24/7"],
    plans: [
      { id: "p7", type: "DAY", price: 150 },
      { id: "p8", type: "WEEK", price: 700 },
      { id: "p9", type: "MONTH", price: 1800 },
    ],
    amenities: ["Locker", "Showers"],
  },
];
